### ISSUE TITLE
More features

### ISSUE THREAD

**Issue by himekifee** [GMTA/btrfs-libs#1]
Hi, this seems to be a great and only project that deal with `btrfs` from `java`. Any further plans for more features? I'd imagine create/delete subvol/snapshot are really handy.

**Comment by gmta** [comment]
Hi @himekifee, currently this library only deals with reading btrfs streams. There is no support to read from or write to btrfs filesystems as of yet, and there are no plans to do so. Feel free to cooperate on adding such support though!
